import { useEffect, useMemo, useState } from 'react'
import './App.css'
import LevelExperience from './LevelExperience.jsx'

const API = import.meta.env.VITE_API_URL || 'http://localhost:4000/api'
const levelsSeed = [
  { id: 1, title: 'Command Line Recon', concept: 'Linux fundamentals', difficulty: 'INITIATE', description: 'Build confidence in a safe, simulated shell environment.', mission: 'Locate the training server evidence file without touching a real filesystem.', xp: 100, coins: 50, tasks: [{ prompt: 'Use pwd to reveal your simulated location.', answer: 'pwd' }, { prompt: 'List the simulated workspace contents.', answer: 'ls' }, { prompt: 'Read evidence.txt to complete the objective.', answer: 'cat evidence.txt' }] },
  { id: 2, title: 'Signal in the Noise', concept: 'Log analysis', difficulty: 'OPERATIVE', description: 'Learn to spot authentication patterns in structured server records.', mission: 'Find the suspicious authentication sequence in the simulated access log.', xp: 120, coins: 60, tasks: [{ prompt: 'Search access.log for failed entries.', answer: 'grep failed access.log' }, { prompt: 'List all investigation files.', answer: 'ls' }] },
  { id: 3, title: 'The Input Boundary', concept: 'Web security concepts', difficulty: 'ANALYST', description: 'Practice reasoning about validation, authentication, and safe application design.', mission: 'Identify which controls protect a simulated web form.', xp: 130, coins: 65, tasks: [{ prompt: 'Inspect the form control notes.', answer: 'cat controls.txt' }, { prompt: 'Confirm the validation checklist.', answer: 'grep validation controls.txt' }] },
  { id: 4, title: 'Packet Watch', concept: 'Network security', difficulty: 'SPECIALIST', description: 'Understand ports, protocols, and suspicious traffic patterns.', mission: 'Classify the simulated event and recommend a containment action.', xp: 140, coins: 70, tasks: [{ prompt: 'Review the simulated traffic table.', answer: 'cat traffic.txt' }, { prompt: 'Filter for the suspicious event.', answer: 'grep suspicious traffic.txt' }] },
  { id: 5, title: 'Blackout Protocol', concept: 'Incident response', difficulty: 'COMMANDER', description: 'Build an evidence-led response to a simulated security incident.', mission: 'Reconstruct the timeline and select the first response actions.', xp: 150, coins: 75, tasks: [{ prompt: 'Read the incident timeline.', answer: 'cat timeline.txt' }, { prompt: 'Find the containment recommendation.', answer: 'grep contain timeline.txt' }] },
]
levelsSeed.push(
  { id: 6, title: 'Code Under Glass', concept: 'Web security basics II', difficulty: 'ANALYST', description: 'Recognize safe and unsafe patterns in a simulated application review.', mission: 'Identify the validation and output-encoding controls in a code review.', xp: 160, tasks: [{ prompt: 'Inspect the code review notes.', answer: 'cat review.txt' }, { prompt: 'Filter for the encoding control.', answer: 'grep encoding review.txt' }] },
  { id: 7, title: 'Protocol Atlas', concept: 'Network security I', difficulty: 'SPECIALIST', description: 'Map simulated ports and protocols to their intended roles.', mission: 'Identify the protocol used by each simulated service.', xp: 170, tasks: [{ prompt: 'Review the service map.', answer: 'cat services.txt' }, { prompt: 'Find the HTTPS service.', answer: 'grep https services.txt' }] },
  { id: 8, title: 'Watchtower', concept: 'Network security II', difficulty: 'SPECIALIST', description: 'Use defensive signals to recognize suspicious traffic patterns.', mission: 'Find the event that should trigger an alert.', xp: 180, tasks: [{ prompt: 'Read the alert rules.', answer: 'cat alerts.txt' }, { prompt: 'Filter for the beacon rule.', answer: 'grep beacon alerts.txt' }] },
  { id: 9, title: 'Evidence Locker', concept: 'Incident response I', difficulty: 'COMMANDER', description: 'Preserve evidence and reconstruct a simulated compromise.', mission: 'Identify the first evidence-preservation action.', xp: 190, tasks: [{ prompt: 'Read the response checklist.', answer: 'cat response.txt' }, { prompt: 'Find the preserve action.', answer: 'grep preserve response.txt' }] },
  { id: 10, title: 'Root Cause', concept: 'Incident response II', difficulty: 'COMMANDER', description: 'Complete a full simulated response from timeline to remediation.', mission: 'Determine root cause and select the final remediation step.', xp: 200, tasks: [{ prompt: 'Read the final incident report.', answer: 'cat final-report.txt' }, { prompt: 'Find the remediation action.', answer: 'grep remediate final-report.txt' }] },
)
async function request(path, options = {}) { const { token, ...fetchOptions } = options; const response = await fetch(`${API}${path}`, { headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) }, ...fetchOptions }); if (!response.ok) throw new Error((await response.json()).error || 'Request failed'); return response.json() }
function App() {
  const [session, setSession] = useState(() => JSON.parse(localStorage.getItem('cyber-session') || 'null'))
  const [levels, setLevels] = useState(levelsSeed)
  const [progress, setProgress] = useState(() => JSON.parse(localStorage.getItem('cyber-progress') || '[]'))
  const [activeLevel, setActiveLevel] = useState(null)
  const [view, setView] = useState('dashboard')
  const [loading, setLoading] = useState(false)
  useEffect(() => { if (session) { request('/levels', { token: session.token }).then((data) => setLevels(data.levels)).catch(() => {}); request('/progress', { token: session.token }).then((data) => setProgress(data.progress)).catch(() => {}) } }, [session])
  const completed = progress.filter((item) => item.completed).length
  const xp = progress.reduce((sum, item) => sum + (item.xp_earned || 0), 0)
  const coins = progress.reduce((sum, item) => sum + (item.coins_earned || (item.completed ? Math.round((item.xp_earned || 0) / 2) : 0)), 0)
  const unlocks = useMemo(() => levels.map((level, index) => ({ ...level, unlocked: index === 0 || Boolean(progress.find((item) => item.level_id === level.id - 1)?.completed), completed: Boolean(progress.find((item) => item.level_id === level.id)?.completed) })), [levels, progress])
  const authenticate = async (mode, fields) => { setLoading(true); try { const data = await request(`/auth/${mode}`, { method: 'POST', body: JSON.stringify(fields) }); localStorage.setItem('cyber-session', JSON.stringify(data)); setSession(data) } catch (error) { alert(error.message) } finally { setLoading(false) } }
  const completeTask = async (levelId, taskCount) => { const level = levels[levelId - 1]; const next = progress.filter((item) => item.level_id !== levelId).concat({ level_id: levelId, tasks_completed: taskCount, completed: taskCount === level.tasks.length, xp_earned: taskCount === level.tasks.length ? level.xp : 0 }); setProgress(next); localStorage.setItem('cyber-progress', JSON.stringify(next)); if (session) request('/progress', { method: 'POST', token: session.token, body: JSON.stringify({ levelId, tasksCompleted: taskCount }) }).catch(() => {}) }
  if (!session) return <AuthScreen onSubmit={authenticate} loading={loading} />
  if (view !== 'dashboard') return <main className="app-shell"><Header session={session} view={view} setView={setView} unlocked={completed === 10} onLogout={() => { localStorage.removeItem('cyber-session'); setSession(null) }} /><AuxiliaryView view={view} session={session} completed={completed} xp={xp} coins={coins} unlocked={completed === 10} /></main>
  return <main className="app-shell"><Header session={session} view={view} setView={setView} unlocked={completed === 10} onLogout={() => { localStorage.removeItem('cyber-session'); setSession(null) }} /><section className="hero-row"><div><p className="eyebrow">OPERATIVE CONSOLE <span>▸</span> OVERVIEW</p><h1>Good morning, <em>{session.user.username}</em>.</h1><p className="lede">Ten controlled environments. One evidence-led path to mastery.</p></div><div className="hero-stamp"><span>FIELD<br />READY</span><strong>{String(completed).padStart(2, '0')}<small>/10</small></strong></div></section><section className="metrics"><Metric label="TOTAL XP" value={xp.toLocaleString()} accent="lime" /><Metric label="COINS" value={coins.toLocaleString()} accent="amber" /><Metric label="LABS CLEARED" value={`${completed} / 10`} accent="cyan" /><Metric label="READINESS" value={`${Math.round(completed / 10 * 100)}%`} accent="pink" /></section><div className="section-heading"><div><p className="eyebrow">TRAINING ARCHIVE / 10 MODULES</p><h2>Mission sequence</h2></div><span className="sequence-line" /></div><section className="mission-grid">{unlocks.map((level) => <MissionCard key={level.id} level={level} onOpen={() => level.unlocked && setActiveLevel(level)} />)}</section><footer className="safety-note"><span>◈</span><div><strong>SIMULATION BOUNDARY</strong><p>Every command runs in a sealed educational model. No host shell, real filesystem, or external network is reachable.</p></div></footer>{activeLevel && <LevelExperience level={activeLevel} onClose={() => setActiveLevel(null)} onComplete={completeTask} />}</main>
}
function Header({ view, setView, unlocked, onLogout }) { return <header className="topbar"><Brand /><nav className="nav-links"><button className={view === 'dashboard' ? 'active' : ''} onClick={() => setView('dashboard')}>DASHBOARD</button><button className={view === 'profile' ? 'active' : ''} onClick={() => setView('profile')}>PROFILE</button><button className={view === 'store' ? 'active' : ''} onClick={() => setView('store')}>STORE</button><button className="gated" disabled={!unlocked} onClick={() => setView('dual')}>DUAL MODE</button><button className="gated" disabled={!unlocked} onClick={() => setView('clan')}>CLAN</button></nav><div className="top-actions"><span className="status-dot">● ONLINE</span><button className="ghost-button" onClick={onLogout}>SIGN OUT</button></div></header> }
function Brand() { return <div className="brand-mark"><span>CD</span><div><strong>CYBER DOMINION</strong><small>SIMULATION NETWORK / 01</small></div></div> }
function AuxiliaryView({ view, session, completed, xp, coins, unlocked }) { if (view === 'profile') return <section className="aux-page"><p className="eyebrow">OPERATIVE RECORD</p><h1>{session.user.username}<em>.</em></h1><div className="profile-grid"><Metric label="CURRENT LEVEL" value={Math.min(completed + 1, 10)} accent="lime" /><Metric label="TOTAL XP" value={xp} accent="cyan" /><Metric label="COINS" value={coins} accent="amber" /><Metric label="COMPLETION" value={`${completed}/10`} accent="pink" /></div><div className="panel-copy"><p className="eyebrow">ACHIEVEMENTS</p><h2>Earned signals</h2><p>{completed > 0 ? 'First Signal · Level completion badge unlocked.' : 'Complete your first mission to unlock your first badge.'}</p></div></section>; if (view === 'store') return <section className="aux-page"><p className="eyebrow">REWARD EXCHANGE</p><h1>Field store<em>.</em></h1><p className="lede">Spend earned coins on cosmetic training surfaces. Purchases are local MVP inventory until the store API is connected.</p><div className="store-grid"><StoreItem name="Neon Terminal" cost="200" icon="⌁" /><StoreItem name="Defender Frame" cost="150" icon="◇" /><StoreItem name="XP Booster" cost="500" icon="+" /></div></section>; return <section className="aux-page locked-mode"><p className="eyebrow">COMPETITIVE NETWORK</p><h1>{view === 'dual' ? 'Dual mode' : 'Clan mode'}<em>.</em></h1><div className="unlock-panel"><span>{unlocked ? '◈' : '🔒'}</span><h2>{unlocked ? 'Mode unlocked.' : 'Complete all 10 levels.'}</h2><p>{unlocked ? 'Competitive services are ready for the next integration slice.' : 'Finish the foundational sequence to unlock competitive challenges and clan management.'}</p></div></section> }
function StoreItem({ name, cost, icon }) { return <article className="store-item"><span>{icon}</span><h3>{name}</h3><p>Cosmetic system upgrade</p><strong>{cost} COINS</strong><button className="primary-button" disabled>COMING SOON</button></article> }
function AuthScreen({ onSubmit, loading }) { const [mode, setMode] = useState('login'); const [fields, setFields] = useState({ username: '', email: '', password: '' }); return <main className="auth-page"><div className="auth-intro"><Brand /><p className="eyebrow">A CONTROLLED LEARNING ENVIRONMENT</p><h1>Think like<br /><em>defense.</em></h1><p className="lede">Build the instincts that keep systems standing. Five progressive missions, zero real-world risk.</p><div className="signal-bar"><span>01</span><i /><span>05</span></div></div><form className="auth-card" onSubmit={(event) => { event.preventDefault(); onSubmit(mode, fields) }}><p className="eyebrow">{mode === 'login' ? 'RETURNING OPERATIVE' : 'NEW OPERATIVE'}</p><h2>{mode === 'login' ? 'Enter the network.' : 'Claim your callsign.'}</h2>{mode === 'register' && <label>CALLSIGN<input required value={fields.username} onChange={(e) => setFields({ ...fields, username: e.target.value })} placeholder="e.g. nightwatch" /></label>}<label>EMAIL<input required type="email" value={fields.email} onChange={(e) => setFields({ ...fields, email: e.target.value })} placeholder="operative@domain.test" /></label><label>PASSCODE<input required minLength="8" type="password" value={fields.password} onChange={(e) => setFields({ ...fields, password: e.target.value })} placeholder="8+ characters" /></label><button className="primary-button" disabled={loading}>{loading ? 'AUTHENTICATING...' : mode === 'login' ? 'ACCESS COMMAND CENTER →' : 'CREATE OPERATIVE →'}</button><button type="button" className="switch-button" onClick={() => setMode(mode === 'login' ? 'register' : 'login')}>{mode === 'login' ? 'Need an account? Register' : 'Already registered? Sign in'}</button></form></main> }
function Metric({ label, value, accent }) { return <div className={`metric ${accent}`}><span>{label}</span><strong>{value}</strong><i /></div> }
function MissionCard({ level, onOpen }) { return <article className={`mission-card ${level.unlocked ? '' : 'locked'} ${level.completed ? 'cleared' : ''}`} onClick={onOpen}><div className="card-top"><span className="level-number">0{level.id}</span><span>{level.unlocked ? level.completed ? 'CLEARED' : 'AVAILABLE' : 'LOCKED'} {level.unlocked ? '↗' : '●'}</span></div><h3>{level.title}</h3><p>{level.concept}</p><div className="card-bottom"><span>{level.difficulty}</span><span>{level.xp} XP</span></div>{level.unlocked && <div className="card-progress"><i style={{ width: `${level.completed ? 100 : 8}%` }} /></div>}</article> }
function LabModal({ level, onClose, onComplete }) { const [task, setTask] = useState(0); const [command, setCommand] = useState(''); const [output, setOutput] = useState('SIMULATOR READY. Type help for allowed commands.'); const [done, setDone] = useState(false); const run = (event) => { event.preventDefault(); const normalized = command.trim().toLowerCase().replace(/"/g, ''); const current = level.tasks[task]; const matches = normalized === current.answer; setOutput(matches ? `✓ OBJECTIVE VERIFIED\n${command}\n${outputFor(command)}` : '× No match. The simulator accepted the command but this objective is still open.'); if (matches) { if (task + 1 === level.tasks.length) { setDone(true); onComplete(level.id, level.tasks.length) } else setTask(task + 1) } setCommand('') }; return <div className="modal-backdrop"><section className="lab-modal"><button className="close-button" onClick={onClose}>×</button><div className="lab-header"><p className="eyebrow">LEVEL 0{level.id} / {level.difficulty}</p><h2>{level.title}</h2><p>{level.mission}</p></div>{done ? <div className="complete-state"><span>✦</span><p className="eyebrow">MISSION COMPLETE</p><h2>Signal secured.</h2><p>{level.xp} XP added to your operative record. The next module is now available.</p><button className="primary-button" onClick={onClose}>RETURN TO ARCHIVE →</button></div> : <><div className="task-strip"><span>TASK {task + 1} / {level.tasks.length}</span><strong>{level.tasks[task].prompt}</strong><i><b style={{ width: `${task / level.tasks.length * 100}%` }} /></i></div><div className="terminal"><div className="terminal-top"><span>● ● ●</span><small>sealed-shell / training-server</small></div><div className="terminal-output">{output.split('\n').map((line, index) => <div key={index}>{line}</div>)}</div><form onSubmit={run} className="terminal-input"><span>trainee@cd:~$</span><input autoFocus value={command} onChange={(e) => setCommand(e.target.value)} placeholder="enter simulated command" /></form></div></>}</section></div> }
function outputFor(command) { const outputs = { pwd: '/home/trainee/training-server', ls: 'access.log  controls.txt  evidence.txt  timeline.txt  traffic.txt', 'cat evidence.txt': 'CASE-041 | training artifact | rotate the exposed demo key.', 'grep failed access.log': '08:41:02 AUTH failed user=demo source=simulated-client', 'cat controls.txt': 'validation: required | authentication: session-bound | output-encoding: required', 'grep validation controls.txt': 'validation: required', 'cat traffic.txt': '443 HTTPS normal | 4444 TCP suspicious simulated beacon', 'grep suspicious traffic.txt': '4444 TCP suspicious simulated beacon', 'cat timeline.txt': '09:10 alert raised | 09:15 contain the simulated host', 'grep contain timeline.txt': '09:15 contain the simulated host', 'cat review.txt': 'validation: required | output-encoding: required', 'grep encoding review.txt': 'output-encoding: required', 'cat services.txt': '443 HTTPS web | 53 DNS resolver | 22 SSH administration', 'grep https services.txt': '443 HTTPS web', 'cat alerts.txt': 'rule: repeated-auth-failure | rule: simulated-beacon', 'grep beacon alerts.txt': 'rule: simulated-beacon', 'cat response.txt': 'preserve evidence | record timeline | contain simulated host', 'grep preserve response.txt': 'preserve evidence', 'cat final-report.txt': 'root cause: unsafe demo credential | remediate: rotate credential', 'grep remediate final-report.txt': 'remediate: rotate credential and validate controls' }; return outputs[command.trim().toLowerCase().replace(/"/g, '')] || 'simulated output' }
export default App
