import mysql from 'mysql2/promise'
import bcrypt from 'bcryptjs'

export const levels = [
  { id: 1, title: 'Command Line Recon', concept: 'Linux fundamentals', difficulty: 'INITIATE', description: 'Build confidence in a safe, simulated shell environment.', mission: 'Locate the training server evidence file without touching a real filesystem.', xp: 100, coins: 50, tasks: [{ prompt: 'Use pwd to reveal your simulated location.', answer: 'pwd' }, { prompt: 'List the simulated workspace contents.', answer: 'ls' }, { prompt: 'Read evidence.txt to complete the objective.', answer: 'cat evidence.txt' }] },
  { id: 2, title: 'Signal in the Noise', concept: 'Log analysis', difficulty: 'OPERATIVE', description: 'Learn to spot authentication patterns in structured server records.', mission: 'Find the suspicious authentication sequence in the simulated access log.', xp: 120, coins: 60, tasks: [{ prompt: 'Search access.log for failed entries.', answer: 'grep failed access.log' }, { prompt: 'List all investigation files.', answer: 'ls' }] },
  { id: 3, title: 'The Input Boundary', concept: 'Web security concepts', difficulty: 'ANALYST', description: 'Practice reasoning about validation, authentication, and safe application design.', mission: 'Identify which controls protect a simulated web form.', xp: 130, coins: 65, tasks: [{ prompt: 'Inspect the form control notes.', answer: 'cat controls.txt' }, { prompt: 'Confirm the validation checklist.', answer: 'grep validation controls.txt' }] },
  { id: 4, title: 'Packet Watch', concept: 'Network security', difficulty: 'SPECIALIST', description: 'Understand ports, protocols, and suspicious traffic patterns.', mission: 'Classify the simulated event and recommend a containment action.', xp: 140, coins: 70, tasks: [{ prompt: 'Review the simulated traffic table.', answer: 'cat traffic.txt' }, { prompt: 'Filter for the suspicious event.', answer: 'grep suspicious traffic.txt' }] },
  { id: 5, title: 'Blackout Protocol', concept: 'Incident response', difficulty: 'COMMANDER', description: 'Build an evidence-led response to a simulated security incident.', mission: 'Reconstruct the timeline and select the first response actions.', xp: 150, coins: 75, tasks: [{ prompt: 'Read the incident timeline.', answer: 'cat timeline.txt' }, { prompt: 'Find the containment recommendation.', answer: 'grep contain timeline.txt' }] },
]

levels.push(
  { id: 6, title: 'Code Under Glass', concept: 'Web security basics II', difficulty: 'ANALYST', description: 'Recognize safe and unsafe patterns in a simulated application review.', mission: 'Identify the validation and output-encoding controls in a code review.', xp: 160, coins: 80, tasks: [{ prompt: 'Inspect the code review notes.', answer: 'cat review.txt' }, { prompt: 'Filter for the encoding control.', answer: 'grep encoding review.txt' }] },
  { id: 7, title: 'Protocol Atlas', concept: 'Network security I', difficulty: 'SPECIALIST', description: 'Map simulated ports and protocols to their intended roles.', mission: 'Identify the protocol used by each simulated service.', xp: 170, coins: 85, tasks: [{ prompt: 'Review the service map.', answer: 'cat services.txt' }, { prompt: 'Find the HTTPS service.', answer: 'grep https services.txt' }] },
  { id: 8, title: 'Watchtower', concept: 'Network security II', difficulty: 'SPECIALIST', description: 'Use defensive signals to recognize suspicious traffic patterns.', mission: 'Find the event that should trigger an alert.', xp: 180, coins: 90, tasks: [{ prompt: 'Read the alert rules.', answer: 'cat alerts.txt' }, { prompt: 'Filter for the beacon rule.', answer: 'grep beacon alerts.txt' }] },
  { id: 9, title: 'Evidence Locker', concept: 'Incident response I', difficulty: 'COMMANDER', description: 'Preserve evidence and reconstruct a simulated compromise.', mission: 'Identify the first evidence-preservation action.', xp: 190, coins: 95, tasks: [{ prompt: 'Read the response checklist.', answer: 'cat response.txt' }, { prompt: 'Find the preserve action.', answer: 'grep preserve response.txt' }] },
  { id: 10, title: 'Root Cause', concept: 'Incident response II', difficulty: 'COMMANDER', description: 'Complete a full simulated response from timeline to remediation.', mission: 'Determine root cause and select the final remediation step.', xp: 200, coins: 100, tasks: [{ prompt: 'Read the final incident report.', answer: 'cat final-report.txt' }, { prompt: 'Find the remediation action.', answer: 'grep remediate final-report.txt' }] },
)

const learningGuides = [
  { time: '15-20 min', objectives: ['Navigate a simulated Linux filesystem', 'Read files safely', 'Choose commands based on their purpose'], why: 'SOC analysts and incident responders use basic navigation and file inspection to orient themselves during investigations.', terms: [['pwd', 'Prints the current simulated directory.'], ['ls', 'Lists simulated files and directories.'], ['cat', 'Reads simulated text content.']], mistakes: 'Using cd when you only need to see your current location.', hints: ['Think about the command that shows your current location.', 'Which command displays the working directory?', 'Try: pwd'], quiz: [{ question: 'Which command shows your current working directory?', options: ['ls', 'pwd', 'cd', 'cat'], answer: 1, explanation: 'pwd prints the present working directory.' }, { question: 'Which command lists simulated files?', options: ['ls', 'pwd', 'echo', 'cd'], answer: 0, explanation: 'ls lists the contents of the current simulated directory.' }, { question: 'Which command reads text content?', options: ['find', 'cat', 'chmod', 'pwd'], answer: 1, explanation: 'cat displays the contents of a text file in the simulator.' }] },
  { time: '15-20 min', objectives: ['Recognize hidden files', 'Interpret permission notation', 'Filter simulated text'], why: 'Permission and file inspection skills help analysts understand what a process or account can access.', terms: [['ls -la', 'Lists hidden files with permission details.'], ['grep', 'Filters lines that match a term.'], ['find', 'Searches the simulated tree.']], mistakes: 'Treating a hidden file as deleted; hidden only changes how it is displayed.', hints: ['Look for the long listing command.', 'The command needs a flag that includes hidden files.', 'Try: ls -la'], quiz: [{ question: 'Which flag reveals hidden files in a long listing?', options: ['-h', '-la', '-r', '-x'], answer: 1, explanation: 'The simulated -la form shows hidden entries and details.' }, { question: 'What does grep do?', options: ['Changes permissions', 'Filters matching lines', 'Moves folders', 'Shows current location'], answer: 1, explanation: 'grep filters text for a matching term.' }, { question: 'What does a hidden file mean?', options: ['It is deleted', 'It is encrypted', 'It is omitted from a normal listing', 'It cannot be read'], answer: 2, explanation: 'Hidden files are still present; they are omitted from a normal listing.' }] },
]
levels.forEach((level) => { level.coins ??= Math.round(level.xp / 2); level.guide = learningGuides[level.id - 1] || { time: '20-25 min', objectives: ['Read the briefing', 'Interpret simulated evidence', 'Choose a defensive conclusion'], why: 'This skill supports evidence-led decisions by cybersecurity professionals.', terms: [['evidence', 'A fictional artifact used for investigation.'], ['indicator', 'A clue that helps describe an event.']], mistakes: 'Jumping to conclusions before comparing multiple pieces of evidence.', hints: ['Start with the file named in the task.', 'Read the evidence before selecting a conclusion.', 'Use the task prompt as your search term.'], quiz: [{ question: 'What is the safest first step in a simulated investigation?', options: ['Destroy evidence', 'Read and preserve evidence', 'Attack the source', 'Run host commands'], answer: 1, explanation: 'Evidence-led work starts by reading and preserving fictional artifacts.' }, { question: 'What is an indicator?', options: ['A clue about an event', 'A real exploit', 'A password', 'A shell command'], answer: 0, explanation: 'An indicator is a clue that helps describe a fictional event.' }, { question: 'What should a responder do before concluding?', options: ['Compare evidence', 'Delete logs', 'Attack a target', 'Run host commands'], answer: 0, explanation: 'Comparing evidence reduces assumptions and supports careful decisions.' }] } })

const achievements = [{ id: 1, name: 'First Signal', description: 'Complete your first lab', icon: '◎' }, { id: 2, name: 'Log Reader', description: 'Complete Log Analysis', icon: '◌' }, { id: 3, name: 'Command Ready', description: 'Complete all five labs', icon: '✦' }]
const memory = { users: [], progress: new Map() }
let pool

export async function initStore() {
  if (!process.env.MYSQL_HOST) return false
  try {
    pool = await mysql.createPool({ host: process.env.MYSQL_HOST, port: Number(process.env.MYSQL_PORT || 3306), user: process.env.MYSQL_USER, password: process.env.MYSQL_PASSWORD, database: process.env.MYSQL_DATABASE, connectionLimit: 5 })
    await pool.query('SELECT 1')
    return true
  } catch { pool = undefined; return false }
}
export const usingDatabase = () => Boolean(pool)
export async function findUserByEmail(email) { if (pool) { const [rows] = await pool.query('SELECT * FROM users WHERE email = ?', [email]); return rows[0] } return memory.users.find((user) => user.email === email) }
export async function findUserById(id) { if (pool) { const [rows] = await pool.query('SELECT id, username, email, created_at FROM users WHERE id = ?', [id]); return rows[0] } return memory.users.find((user) => user.id === Number(id)) }
export async function createUser({ username, email, password }) { const passwordHash = await bcrypt.hash(password, 10); if (pool) { const [result] = await pool.query('INSERT INTO users (username,email,password_hash) VALUES (?,?,?)', [username, email, passwordHash]); return { id: result.insertId, username, email, password_hash: passwordHash } } const user = { id: memory.users.length + 1, username, email, password_hash: passwordHash, created_at: new Date().toISOString() }; memory.users.push(user); return user }
export async function getProgress(userId) { if (pool) { const [rows] = await pool.query('SELECT * FROM user_progress WHERE user_id = ?', [userId]); return rows } return levels.map((level) => memory.progress.get(`${userId}:${level.id}`) || { user_id: userId, level_id: level.id, completed: false, tasks_completed: 0, xp_earned: 0 }) }
export async function saveProgress(userId, levelId, tasksCompleted, completed) { const level = levels.find((item) => item.id === Number(levelId)); const xp = completed ? level.xp : 0; const coins = completed ? (level.coins || Math.round(level.xp / 2)) : 0; if (pool) { await pool.query('INSERT INTO user_progress (user_id,level_id,tasks_completed,completed,xp_earned,coins_earned,completed_at) VALUES (?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE tasks_completed=VALUES(tasks_completed),completed=VALUES(completed),xp_earned=VALUES(xp_earned),coins_earned=VALUES(coins_earned),completed_at=VALUES(completed_at)', [userId, levelId, tasksCompleted, completed, xp, coins, completed ? new Date() : null]); } else memory.progress.set(`${userId}:${levelId}`, { user_id: userId, level_id: Number(levelId), completed, tasks_completed: tasksCompleted, xp_earned: xp, coins_earned: coins }) ; return { level_id: Number(levelId), completed, tasks_completed: tasksCompleted, xp_earned: xp, coins_earned: coins }
}
export { achievements }
